### ISSUE TITLE
Vulnerability Inventory table doesn't scroll

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#7101]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.0 | 00 | Chrome, Firefox, Safari, etc |

**Description**

The table in Vulnerabilities / Inventory view doesn't scroll whenever the amount of rows per page is greater than 15.

The issue seems to be located in this style
```css
.vulsInventoryContainer .vulsInventoryDataGrid {
    height: calc(100vh - 216px) !important;
}
```
Related code:
https://github.com/wazuh/wazuh-dashboard-plugins/blob/v4.9.0/plugins/main/public/components/overview/vulnerabilities/dashboards/inventory/inventory.scss#L9-L11

![Peek 2024-10-16 18-35](https://github.com/user-attachments/assets/11d7bec5-0532-415e-9648-de34b5ef9895)
