### ISSUE TITLE
Improve horizontal scroll bar in discover plugin

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#7330]
# Discover

Whenever the Discover plugin has many columns that exceed the viewport width, the horizontal scrollbar is not very accessible because it's at the bottom of the table. We have to improve the user experience so that scrolling horizontally in the table is easier and more intuitive.

![Image](https://github.com/user-attachments/assets/1517ddc4-40f5-4f99-8717-1f2ec5789325)

**Comment by guidomodarelli** [comment]
# Wazuh-dashboard-plugins 4.8.2

https://github.com/user-attachments/assets/f9d78a9f-7e4e-4288-af53-5c6d960d04f4

**Comment by asteriscos** [comment]
May be you can try adding media query to dynamically adjust the height of the table using calc(). You can try to do something like this:

```css
@media (min-width: 992px) {
 .dscCanvas > .dscCanvas_results > div:nth-child(2){
  max-height: calc(100vh - 462px);
 }
}
@media (min-width: 1174px) {
.dscCanvas > .dscCanvas_results > div:nth-child(2){
  max-height: calc(100vh - 422px);
}
}
```

![Image](https://github.com/user-attachments/assets/abdc74f4-8e05-4254-b2e4-00e64e800b57)

**Comment by guidomodarelli** [comment]
```css
.dscCanvas > .dscCanvas_results {
  display: flex;
  flex-direction: column;
}

.dscCanvas > .dscCanvas_results > div:nth-child(2) {
  min-height: 267px;
}

@media (min-width: 992px) {
  .dscCanvas > .dscCanvas_results {
    display: flex;
    flex-direction: column;
    height: calc(100vh - 195px);
  }
}

@media (min-width: 1174px) {
  .dscCanvas > .dscCanvas_results {
    display: flex;
    flex-direction: column;
    height: calc(100vh - 155px);
  }
}
```
