### ISSUE TITLE
Remove hosts configuration from opensearch_dashboards.yml file

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#7345]
# Description

The API hosts configuration is no longer needed, therefore we have to remove it from the opensearch_dashboards.yml configuration file and also delete any validation or reference to it.

The expected default opensearch_dashboards.yml configuration file is:

```yaml
server.host: 0.0.0.0
server.port: 443

opensearch.hosts: https://localhost:9200/
opensearch.ssl.verificationMode: certificate
opensearch.requestHeadersAllowlist: ["securitytenant","Authorization"]
opensearch_security.multitenancy.enabled: false
opensearch_security.readonly_mode.roles: ["kibana_read_only"]

server.ssl.enabled: true
server.ssl.key: "/etc/wazuh-dashboard/certs/dashboard-key.pem"
server.ssl.certificate: "/etc/wazuh-dashboard/certs/dashboard.pem"

opensearch.ssl.certificateAuthorities: ["/etc/wazuh-dashboard/certs/root-ca.pem"]
uiSettings.overrides.defaultRoute: /app/home
```
